### ISSUE TITLE
Generate types for the "app" part

### ISSUE THREAD

**Issue by degroote22** [graphql-boilerplates/typescript-graphql-server#273]
I'm currently using graphql-code-generator to generate types for the "app" part of the code and the experience is awesome.

It gives me the types for the public api which I can export for the front-end and use on the server code itself.
With these dependencies:
```
    "graphql-code-generator": "^0.9.1",
    "graphql-codegen-typescript-template": "^0.9.1",
    "graphql-import": "^0.6.0",
```
We need to join the schemas because of this kind of modular graphql schema used with prisma,
so we create src/importSchema.ts
```typescript
import { importSchema } from "graphql-import";
export default importSchema("./src/schema.graphql");
```
Automate it in prisma.yml:
```yaml
hooks:
  post-deploy:
    - graphql get-schema --project database
    - graphql codegen
    - gql-gen --require ts-node/register --template typescript --export ./src/importSchema.ts --out ./src/typings/
```

and we can use the types like so, in Query.ts (strict Typescript :+1: )
```typescript
import { PostQueryArgs } from "../typings/types";
// later...
  post(
    parent: never,
    { id }: PostQueryArgs, // type generated now
    ctx: Context,
    info: never
  ) {
    return ctx.db.query.post({ where: { id: id } }, info);
  },
```

This approach should be added here, like this or with apollo-codegen (which I couldn't get to work like this). It helped me catch a bug where I had a "string" on the app part and a "string!" on the database part, for instance.

**Comment by Sharlaan** [comment]
Would it work like this ?  

in `.graphqlconfig.yml`  
```yaml
app:
    schemaPath: src/schema.graphql
    includes: ["**/*.graphql"]
    extensions:
      endpoints:
        default: ${env:API_PROTOCOL}://${env:API_HOST}:${env:API_PORT}
      codegen:
        - generator: prisma-binding
          language: typescript
          output:
            binding: src/generated/api.ts
```

then reference api-side types in resolvers with
`import { Query } from '../../generated/api';`

Would not it be cleaner and less dependencies ?
